name: specvqgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - abseil-cpp
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - altair=4.1.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow-cpp=4.0.0
  - astor=0.8.1
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - audioread=2.1.9
  - autopep8=1.5.6
  - aws-c-cal=0.4.5
  - aws-c-common=0.5.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.9.1
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.151
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - base58=2.1.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - boto3=1.17.59
  - botocore=1.20.59
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - c-ares=1.17.1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3.1
  - flake8=3.9.0
  - freetype=2.10.4
  - fsspec=2021.4.0
  - future=0.18.2
  - gettext=0.19.8.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.15
  - glog=0.4.0
  - google-auth=1.28.0
  - google-auth-oauthlib=0.4.1
  - grpc-cpp=1.37.0
  - grpcio=1.37.0
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - importlib-metadata=4.0.1
  - ipykernel=5.5.5
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.12
  - libcurl=7.76.1
  - libevent=2.1.10
  - libffi=3.3
  - libflac=1.3.3
  - libiconv=1.16
  - libllvm10=10.0.1
  - libnghttp2
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - librosa=0.8.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.14.1
  - libtiff=4.1.0
  - libutf8proc=2.6.1
  - libuv=1.41.0
  - libvorbis=1.3.7
  - llvm-openmp=11.1.0
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib-base=3.4.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.0
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.3.0
  - numba=0.53.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - omegaconf=2.0.6
  - openh264
  - openssl=1.1.1k
  - orc=1.6.7
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1
  - pooch=1.3.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - protobuf=3.15.8
  - ptyprocess=0.7.0
  - pyarrow=4.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydeck=0.5.0
  - pyflakes=2.2.0
  - pygments=2.8.1
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pysoundfile=0.10.3
  - python=3.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.8.1
  - pytorch-lightning=1.2.10
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - re2=2021.04.01
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - resampy=0.2.2
  - rsa=4.7.2
  - s3transfer=0.4.2
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sqlite=3.35.5
  - streamlit=0.80.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.8.1
  - torchmetrics=0.3.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzlocal=2.1
  - urllib3=1.26.4
  - validators=0.18.2
  - watchdog=2.0.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - x264
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - albumentations==0.5.2
    - decorator==4.4.2
    - imgaug==0.4.0
    - networkx==2.5.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.5.1.48
    - pywavelets==1.1.1
    - scikit-image==0.18.1
    - shapely==1.7.1
    - test-tube==0.7.5
    - tifffile==2021.4.8
